#!/usr/bin/env python3
"""
Generate a batch traceability report as a Word document and upload to SharePoint.

Usage:
    python generate_batch_report.py --tenant-id tenant_001 --config tenant_config.json \
        --lot-number Lot-2847 --product "Mango Puree 500ml"
"""

import os
import sys
import json
import time
import argparse
from datetime import datetime
import msal
import requests

try:
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.table import WD_TABLE_ALIGNMENT
except ImportError:
    print("Install python-docx: pip install python-docx", file=sys.stderr)
    sys.exit(1)


def get_token(tenant_id, client_id, key_path):
    with open(key_path) as f:
        private_key = f.read()
    app = msal.ConfidentialClientApplication(
        client_id,
        authority=f"https://login.microsoftonline.com/{tenant_id}",
        client_credential={"thumbprint": os.environ["M365_CERT_THUMBPRINT"], "private_key": private_key},
    )
    result = app.acquire_token_for_client(scopes=["https://graph.microsoft.com/.default"])
    if "access_token" not in result:
        raise RuntimeError(f"Auth failed: {result.get('error_description')}")
    return result["access_token"]


def build_report(batch_data: dict, output_path: str):
    """Generate a Word document batch report."""
    doc = Document()

    # Title
    doc.add_heading(f"Batch Traceability Report", 0)
    doc.add_heading(f"Lot: {batch_data['lot_number']} — {batch_data['product']}", level=1)

    # Metadata
    doc.add_paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    doc.add_paragraph(f"Generated by: Autonomi Quality Agent")
    doc.add_paragraph("")

    # Summary section
    doc.add_heading("Batch Summary", level=2)
    summary_table = doc.add_table(rows=0, cols=2)
    summary_table.style = "Table Grid"
    for key, value in batch_data.get("summary", {}).items():
        row = summary_table.add_row().cells
        row[0].text = key
        row[1].text = str(value)

    # Quality results
    doc.add_heading("Quality Control Results", level=2)
    qc_results = batch_data.get("qc_results", [])
    if qc_results:
        qc_table = doc.add_table(rows=1, cols=5)
        qc_table.style = "Table Grid"
        qc_table.alignment = WD_TABLE_ALIGNMENT.CENTER
        hdr = qc_table.rows[0].cells
        hdr[0].text, hdr[1].text, hdr[2].text = "Test", "Result", "Spec Min"
        hdr[3].text, hdr[4].text = "Spec Max", "Pass/Fail"

        for test in qc_results:
            row = qc_table.add_row().cells
            row[0].text = test["name"]
            row[1].text = str(test["value"])
            row[2].text = str(test.get("spec_min", ""))
            row[3].text = str(test.get("spec_max", ""))
            passed = test.get("spec_min", 0) <= test["value"] <= test.get("spec_max", float("inf"))
            row[4].text = "PASS" if passed else "FAIL"

    # Ingredient traceability
    doc.add_heading("Ingredient Traceability", level=2)
    ingredients = batch_data.get("ingredients", [])
    if ingredients:
        ing_table = doc.add_table(rows=1, cols=4)
        ing_table.style = "Table Grid"
        hdr = ing_table.rows[0].cells
        hdr[0].text, hdr[1].text = "Ingredient", "Supplier"
        hdr[2].text, hdr[3].text = "Lot Number", "Quantity"

        for ing in ingredients:
            row = ing_table.add_row().cells
            row[0].text = ing["name"]
            row[1].text = ing["supplier"]
            row[2].text = ing["lot_number"]
            row[3].text = f"{ing['quantity']} {ing['unit']}"

    # Production notes
    doc.add_heading("Production Notes", level=2)
    for note in batch_data.get("notes", []):
        doc.add_paragraph(f"• {note}")

    # Footer
    doc.add_paragraph("")
    doc.add_paragraph("This report was automatically generated by Autonomi's Quality Agent. "
                      "For questions, contact your Autonomi administrator.")

    doc.save(output_path)
    return output_path


def upload_to_sharepoint(drive_id, folder_path, filename, file_path, headers):
    """Upload the report to SharePoint."""
    with open(file_path, "rb") as f:
        content = f.read()

    if len(content) < 4 * 1024 * 1024:
        resp = requests.put(
            f"https://graph.microsoft.com/v1.0/drives/{drive_id}/items/"
            f"root:{folder_path}/{filename}:/content",
            headers={**headers, "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
            data=content,
        )
        resp.raise_for_status()
        return resp.json()
    else:
        raise NotImplementedError("Large file upload not implemented in this script — see references/sharepoint.md")


def main():
    parser = argparse.ArgumentParser(description="Generate batch report and upload to SharePoint")
    parser.add_argument("--tenant-id", required=True)
    parser.add_argument("--config", required=True)
    parser.add_argument("--lot-number", required=True)
    parser.add_argument("--product", required=True)
    args = parser.parse_args()

    with open(args.config) as f:
        config = json.load(f)

    # In production, this data comes from Autonomi's database
    batch_data = {
        "lot_number": args.lot_number,
        "product": args.product,
        "summary": {
            "Production Date": "2026-03-20",
            "Line": "Line 2",
            "Shift": "Day Shift",
            "Batch Size": "1200 lbs",
            "Yield": "96.2%",
            "Status": "QC Hold",
        },
        "qc_results": [
            {"name": "pH", "value": 3.2, "spec_min": 3.5, "spec_max": 4.0},
            {"name": "Brix", "value": 14.5, "spec_min": 14.0, "spec_max": 16.0},
            {"name": "Color (L*)", "value": 52.1, "spec_min": 48.0, "spec_max": 56.0},
            {"name": "Viscosity (cP)", "value": 320, "spec_min": 280, "spec_max": 380},
        ],
        "ingredients": [
            {"name": "Mango Puree (raw)", "supplier": "Tropical Fruits Co", "lot_number": "TF-2847-A", "quantity": 1300, "unit": "lbs"},
            {"name": "Citric Acid", "supplier": "Chemical Supply Inc", "lot_number": "CS-9921", "quantity": 2.5, "unit": "lbs"},
            {"name": "Ascorbic Acid", "supplier": "Chemical Supply Inc", "lot_number": "CS-9922", "quantity": 1.0, "unit": "lbs"},
        ],
        "notes": [
            "pH reading below spec on sample 3 — triggered automatic QC hold",
            "Brix within spec across all samples",
            "Recommend re-test pH after 24-hour equilibration",
        ],
    }

    # Generate report
    output_path = f"/sandbox/workspace/quality/tmp/batch_report_{args.lot_number}.docx"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    build_report(batch_data, output_path)
    print(f"Report generated: {output_path}")

    # Upload to SharePoint
    drive_id = config["drive_id"]
    root = config["root_folder_name"]
    sp_folder = f"/{root}/Quality/Batch-Reports"
    filename = f"Batch-Report-{args.lot_number}-{datetime.utcnow().strftime('%Y%m%d')}.docx"

    cred_dir = f"/sandbox/credentials/tenant_{args.tenant_id}"
    token = get_token(os.environ["M365_TENANT_ID"], os.environ["M365_CLIENT_ID"], f"{cred_dir}/key.pem")
    headers = {"Authorization": f"Bearer {token}"}

    result = upload_to_sharepoint(drive_id, sp_folder, filename, output_path, headers)
    print(f"Uploaded to SharePoint: {result.get('webUrl', 'unknown')}")


if __name__ == "__main__":
    main()
